### PR TITLE
Extracted and integrated creation date from Google Keep's HTML.

### PR DESCRIPTION
**Pull request by sayzard**
When importing notes from Google Keep, the creation date is not included. 
To solve this issue, after parsing the JSON file, 
I implemented a method to extract the creation date from the corresponding HTML file with the same name.

### CODE REVIEW

**Comment by tgrosinger** [comment]
Hello, thanks for providing this pull request.

I don't think I understand why we need to parse the HTML file to get this information. It seems like the information that we need is in the json already, matches what is in the HTML, and is set correctly when importing the files.

Can you please let us know what operating system you are on where this issue is occurring?

**Review by tgrosinger — COMMENTED** [review]
Hello, thanks for providing this pull request.

I don't think I understand why we need to parse the HTML file to get this information. It seems like the information that we need is in the json already, matches what is in the HTML, and is set correctly when importing the files.

Can you please let us know what operating system you are on where this issue is occurring?

**Comment by sayzard** [comment]
> Hello, thanks for providing this pull request.
> 
> I don't think I understand why we need to parse the HTML file to get this information. It seems like the information that we need is in the json already, matches what is in the HTML, and is set correctly when importing the files.
> 
> Can you please let us know what operating system you are on where this issue is occurring?

The last time I tried, everything imported with the current date and time, so I thought the feature wasn’t working. After trying again today following the update, it’s working fine. I apologize for the confusion.

**Comment by tgrosinger** [comment]
Oh good, glad to hear it's working. Thank you.

**Pull request closed without merging**
